services:
  db:
    image: postgres:15.5
    environment:
      POSTGRES_DB: entrion_development
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    container_name: entrion_app
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: